name: CI build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        otp: ['25.0']
        elixir: ['1.13']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
